### ISSUE TITLE
main.py 更新

### ISSUE THREAD

**Issue by johngao01** [raindrop-hb/douyin_spider#6]
我尝试运行main.py来进行抓包，可是失败了，请问main.py是最新的吗？

**Comment by raindrop-hb** [comment]
需要你自己抓取抖音的cookie填入201行里才能运行
抓取cookie方法：

1. 登录pc抖音
2. **打开链接**[汉堡麻麻的抖音](https://v.douyin.com/i9wQ1ah/)，按住F12，刷新
3. 点击**网络**，**名称**中选第一行，标头，Cookie
![$J GB S$~_SQIDT94NN_QQ7](https://github.com/raindrop-hb/douyin_spider/assets/72308008/0bdeb6d9-43a5-4b90-8e2f-806b84a77178)

**Comment by johngao01** [comment]
是210行吧，我尝试你说的办法填入了cookies，但是运行还是失败，还请你看看：

D:\anaconda3\python.exe F:\python\douyin_spider\main.py 
2023-07-17 11:57:51
github开源地址:https://github.com/raindrop-hb/douyin_spider
使用请保留版权
欢迎使用raindrop抖音爬虫_解析工具
连接更新服务器失败
输入主页链接：https://www.douyin.com/user/MS4wLjABAAAAMPXrsn44tq-G_vNR5aiqbTeRCnBkH1BmSz8AAgj13bU
请输入要采集的作品数,为1即解析最近更新的,其他数即从现在往上爬取,直接回车即爬取全部作品
请输入:1
输入线程数
回车默认4:
Traceback (most recent call last):
  File "F:\python\douyin_spider\main.py", line 239, in <module>
    main()
  File "F:\python\douyin_spider\main.py", line 222, in main
    a = head(a,headers=headers).headers['Location']
  File "D:\anaconda3\lib\site-packages\requests\api.py", line 100, in head
    return request("head", url, **kwargs)
  File "D:\anaconda3\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\anaconda3\lib\site-packages\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "D:\anaconda3\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "D:\anaconda3\lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "D:\anaconda3\lib\site-packages\requests\models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?

**Comment by raindrop-hb** [comment]
如果你要用长链接的话，把217-222这段代码注释掉
原本的代码是在手机复制短链接使用的，例如：**4- 长按复制此条消息，打开抖音搜索，查看TA的更多作品。 https://v.douyin.com/i9wQ1ah/**

a = head(a)
        headers={
            "cookie":cookie()
        }
a = str(a.headers.get('location'))
a = head(a,headers=headers).headers['Location']

**Comment by johngao01** [comment]
有用，这个cookie请问你有测试能用多久吗？

**Comment by raindrop-hb** [comment]
cookie能一直用，如果觉得该项目对您有帮助的话还请给个**star**
