### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by freeze-l** [raindrop-hb/douyin_spider#8]
你好，我运行脚本，输入主页链接和数量之后，会出现如下错误，但是有时候能正常下载不报错，是我的cookie有效期有问题吗？
Traceback (most recent call last):
  File "E:\python\df_plat\douyin\douyin_spider-main\main.py", line 242, in <module>
    main()
  File "E:\python\df_plat\douyin\douyin_spider-main\main.py", line 225, in main
    a = head(a,headers=headers).headers['Location']
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'

**Comment by freeze-l** [comment]
我按照前面的注释过217-222行，注释之后无论我填谁的主页地址，都是下载我自己的主页内容，链接如下的样式
长按复制此条消息，打开抖音搜索，查看TA的更多作品。 https://v.douyin.com/iJhAC9B9/

**Comment by freeze-l** [comment]
a = head(a, headers=headers).headers['Location']我发现这一行返回的headers没有Location字段，所以我把他注释掉了，现在我发现无论我输入谁得主页链接，最终都会显示下载我自己的主页视频，是因为我的cookie问题吗？
